### ISSUE TITLE
code[currentCharToCheck] is a mouthful

### ISSUE THREAD

**Issue by Orangestar12** [arctic5/SLAcompiler#5]
seriously can we agree on a variable name that doesn't take five hours to type

ideas:
 - `code[codePosNum]`
 - `code[codeNo]`
 - `code[number]`
 - `code[position]`

we can just ctrl+h this when we decide.

**Comment by arctic5** [comment]
or you can just pick w/e

**Comment by Orangestar12** [comment]
I don't feel like you're taking this seriously

**Comment by arctic5** [comment]
tbh, not really
